# Generated by Django 2.1.1 on 2018-10-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDPAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.AddField(
            model_name='question',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='isFiltered',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
