# Generated by Django 2.1.1 on 2018-10-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDPAPI', '0002_auto_20181001_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='isFiltered',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
        migrations.AddField(
            model_name='question',
            name='isAppropriate',
            field=models.BooleanField(default=False),
        ),
    ]
