# Generated by Django 2.1.2 on 2018-10-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDPAPI', '0004_authentication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='sessionID',
            field=models.TextField(default=''),
        ),
    ]
