# Generated by Django 2.1.2 on 2018-10-22 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PDPAPI', '0006_auto_20181021_0724'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='MCQOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.TextField(default='')),
                ('totalVotes', models.IntegerField(default=0)),
                ('MCQ_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PDPAPI.MCQ')),
            ],
        ),
    ]
