# Generated by Django 2.1.2 on 2018-11-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDPAPI', '0008_mac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mac',
            name='MCQ_id',
        ),
        migrations.AddField(
            model_name='mac',
            name='MCQ_id',
            field=models.ManyToManyField(to='PDPAPI.MCQ'),
        ),
    ]
