# Generated by Django 2.1.2 on 2018-11-05 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PDPAPI', '0012_auto_20181105_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionvoting',
            name='MCQOption_id',
        ),
    ]
