# Generated by Django 2.1.2 on 2018-11-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDPAPI', '0014_questionvoting'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='open_for_voting',
            field=models.BooleanField(default=True),
        ),
    ]
